sources:
  - name: rom-gnosis
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/rite-of-moloch/rom-develop

plugins:
  - pollingLive:
      defaultInterval: 2000

documents:
  - ./graph/*.graphql
